spring:
  data:
    mongodb:
      database: ${MONGODB_DATABASE:local}
      uri: ${MONGODB_URI:mongodb://localhost:27017}
  banner:
    location: classpath:banner.txt
  rabbitmq:
    addresses: ${MQ_ADDRESSES:amqps://localhost:5672}

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG
    com.github.bucket4j: DEBUG
    com.ced: DEBUG

cors:
  allowed-origins:
    - https://ced.discloud.app
    - http://localhost:4200
    - https://cavernas-e-dragoes.web.app

rate-limit:
  cache:
    expire-after-access: 1h
    maximum-size: 1000
  bandwidth:
    capacity: 100
    refill-interval: 1m
    refill-tokens: 100

amqp:
  exchange-name: ${EXCHANGE_NAME:xD}
  queue-name: ${QUEUE_NAME:xD}
  routing-key: ${ROUTING_KEY:xD}

swagger:
  server: ${SWAGGER_SERVER:http://localhost:8080}
